# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'NearTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearTalk
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'SnapKit'
  pod 'Then'
  pod 'Kingfisher'

  target 'NearTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearTalkUITests' do
    # Pods for testing
  end

end
