# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'NearTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NearTalk
  
  # Rx
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'RxGesture', '~> 4.0.0'
  
  # UI
  pod 'SnapKit', '~> 5.6.0'
  
  # Images
  pod 'Kingfisher', '~> 7.4.1'
  
  # Utils
  pod 'Then', '~> 3.0.0'

  target 'NearTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearTalkUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
  
end
